# Generated by Django 3.1.4 on 2021-01-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210107_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='svg_models',
            field=models.FileField(default='', max_length=1000, upload_to='svgmodels/'),
        ),
    ]
