# Generated by Django 3.1.4 on 2021-01-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210107_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='svg_models',
        ),
        migrations.AddField(
            model_name='productimages',
            name='svg',
            field=models.TextField(default=''),
        ),
    ]
